//! Mnemos Tauri host. `main.rs` is a shim over `run()`; everything real lives
//! here so the crate stays testable and mobile-ready.

pub mod commands;
pub mod error;
pub mod fs;
pub mod logging;
pub mod state;

use tauri::Manager;
use tauri_specta::{collect_commands, collect_events, Builder};

use crate::state::AppState;

/// Where the generated TypeScript bindings land, relative to `src-tauri/`.
/// Checked into git; CI fails if a regen produces a diff (FRONTEND §3).
pub const BINDINGS_PATH: &str = "../bindings/tauri.ts";

/// The single specta registry. Every command and event is registered here
/// exactly once — `collect_commands!` also feeds Tauri's `invoke_handler`, so
/// the two lists cannot drift.
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![commands::ping])
        .events(collect_events![])
}

/// TypeScript emit settings — shared by the dev-time export and the CI check so
/// both produce byte-identical output.
#[cfg(any(debug_assertions, test))]
fn typescript_config() -> specta_typescript::Typescript {
    specta_typescript::Typescript::default()
        .bigint(specta_typescript::BigIntExportBehavior::Number)
        // `@ts-nocheck`: the emitted file carries scaffolding (Channel import,
        // event proxy helper) that is unused until a later wave registers a
        // channel or event, and `noUnusedLocals` would reject it. Exported
        // types stay fully checked at every call site.
        .header("// @generated by tauri-specta. Do not edit by hand.\n// @ts-nocheck\n")
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            let log_dir = crate::fs::paths::logs_dir()?;
            let guard = crate::logging::init(log_dir)?;
            // Held for the process lifetime so buffered log lines are flushed.
            app.manage(guard);

            // Regenerate bindings on every dev boot so a changed Rust signature
            // breaks the TypeScript compile now, not at the next CI run.
            #[cfg(debug_assertions)]
            if let Err(err) = builder.export(typescript_config(), BINDINGS_PATH) {
                tracing::warn!(error = %err, "specta binding export failed");
            }

            let version = app.package_info().version.to_string();
            tracing::info!(component = "host", version = %version, "mnemos starting");
            app.manage(AppState::new(version));

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerates `bindings/tauri.ts`. CI runs this and fails if the working
    /// tree is dirty afterwards, which catches hand-edits and stale bindings.
    #[test]
    fn specta_bindings_are_up_to_date() {
        specta_builder()
            .export(typescript_config(), BINDINGS_PATH)
            .expect("specta bindings must export");
    }
}
