// @generated by tauri-specta. Do not edit by hand.
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Liveness probe: proves the Rust ↔ React bridge and the generated bindings
 * are wired end-to-end.
 */
async ping() : Promise<Result<Pong, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts a recording session: creates the `conversations` row, spawns
 * platform capture (mac sidecar / Windows WASAPI thread via the worker),
 * and starts the worker's live-transcription poll loop. The
 * `idle -> arming -> recording` UI flow: this command is what `arming` waits on.
 */
async startRecording(projectId: string | null) : Promise<Result<StartRecordingResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops capture, transitions the conversation to `Processing`, and kicks
 * off the rest of the pipeline (`transcribe_final` -> extraction -> done)
 * in a detached task so this command returns immediately — the caller
 * navigates to Conversation Detail on `onMutate` and watches
 * `processing-progress` events from there.
 */
async stopRecording(sessionId: number) : Promise<Result<StopRecordingResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forwards the worker's `live_transcript_chunk` broadcast (filtered to this
 * session's conversation) into the Tauri `Channel` React subscribed
 * through — the "reader task" the design docs' Implementation
 * status sections left unbuilt.
 */
async subscribeTranscript(sessionId: number, channel: TAURI_CHANNEL<TranscriptChunk>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_transcript", { sessionId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unsubscribeTranscript(sessionId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unsubscribe_transcript", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forwards this session's `(mic_db, system_db)` broadcast onto the Tauri
 * `Channel` the level meter subscribed through — same shape as
 * `subscribe_transcript` above, but the source is the capture-watch task's
 * broadcast sender (`ActiveSession::level_tx`) rather than a worker topic.
 */
async subscribeMicLevel(sessionId: number, channel: TAURI_CHANNEL<LevelSample>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_mic_level", { sessionId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unsubscribeMicLevel(sessionId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unsubscribe_mic_level", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pauses capture. The capture side genuinely stops writing samples (the
 * Swift sidecar drops sample buffers while paused, and the Windows worker
 * stops its capture) — a pause is a hole in the recording, not a UI-only
 * freeze.
 * 
 * Marking the registry paused *after* the transport succeeds keeps the two
 * from disagreeing when the sidecar refuses: a failed pause leaves the
 * session running, which is what the frontend's own rollback assumes.
 */
async pauseRecording(sessionId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_recording", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resumes capture. See [`pause_recording`] for the ordering rationale.
 */
async resumeRecording(sessionId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_recording", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Crash recovery (12_CORNER_CASES.md "App crashes & recovery" §Mid-recording
 * crash). Called once by the frontend on app launch
 * (`useCrashRecoveryCheck`). A conversation can only be at
 * `status = 'recording'` while a live `ActiveSession` holds it — if that
 * never happened this boot (fresh `RecordingRegistry`, empty), any row
 * still at that status was orphaned by an unclean shutdown of a *previous*
 * run. Trusting `status` alone is safe for exactly this reason: this
 * command's own caller (app boot) always runs before `start_recording` can
 * create a new one this session.
 */
async listInterruptedRecordings() : Promise<Result<Conversation[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_interrupted_recordings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Crash recovery's "Discard" action (12_CORNER_CASES.md, same section).
 * Reuses `StorageService::delete_conversation` — the same atomic,
 * resumable-on-crash delete path `conversation.retry_step`/Conversation
 * Detail's (not-yet-built) delete affordance would use, so a discard that
 * itself gets interrupted mid-delete is cleaned up by the *existing*
 * `resume_pending_deletes()` pass in `lib.rs`'s `setup()` rather than
 * needing its own recovery story.
 */
async discardInterruptedRecording(conversationId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_interrupted_recording", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Crash recovery's "Recover" action (12_CORNER_CASES.md "App crashes &
 * recovery" §Mid-recording crash: "[Recover] runs post-processing on the
 * partial audio"). There is no live `ActiveSession` to resume from — the
 * whole point of "orphaned" is that the process that held one is gone — so
 * this reconstructs just enough of `stop_recording`'s tail to hand the
 * on-disk `mic.wav`/`system.wav` to the exact same
 * `run_post_recording_pipeline` a normal Stop uses, rather than growing a
 * second, parallel post-processing path.
 * 
 * **Corner case — missing/near-empty audio.** A crash before the sidecar
 * ever flushed a chunk (or a conversation folder some other process already
 * touched) can leave `mic.wav`/`system.wav` at zero bytes or a few
 * milliseconds of audio. Running the full pipeline on that produces a
 * "transcription" with nothing in it and an extraction step that has
 * nothing to summarize — a confusing dead end, not a recovered conversation.
 * Follows the same rule as the rest of the pipeline: enqueue
 * `process_conversation` if at least 5s of audio was written, otherwise
 * delete the row. Below that threshold this auto-discards (same atomic path as the
 * "Discard" button) and tells the caller so, instead of offering a Recover
 * that can't recover anything or silently failing the pipeline a few
 * seconds later with a confusing "no speech" result.
 */
async recoverInterruptedRecording(conversationId: string) : Promise<Result<RecoverInterruptedResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recover_interrupted_recording", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The mid-*processing* counterpart to `list_interrupted_recordings`
 * above (12_CORNER_CASES.md "App crashes & recovery" §Mid-processing crash:
 * "This conversation was still processing when Mnemos closed. Continue?").
 * This half of the corner-cases spec was never built: a conversation
 * crashed (or force-quit) mid-`run_post_recording_pipeline` was left at
 * `status = 'processing'` forever, with no boot-time reconciliation and no
 * UI — `ProcessingOverlay` just spins on a `processing-progress` topic
 * nothing will ever publish to again. Same reasoning as the recording-crash
 * case: the registry that would hold a live pipeline task is always empty
 * at boot, so any row still `processing` this early was orphaned by a
 * *previous* run.
 */
async listStuckProcessing() : Promise<Result<Conversation[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_stuck_processing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * "Discard" for a stuck-processing conversation — same atomic delete path
 * as everything else in this file, so a discard interrupted by *another*
 * crash is cleaned up by the existing `resume_pending_deletes()` boot pass.
 */
async discardStuckProcessing(conversationId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_stuck_processing", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * "Continue" for a stuck-processing conversation. Unlike mid-recording
 * recovery there is no partial-audio judgment call to make here — `mic.wav`
 * /`system.wav` are already complete (capture finished normally; it was the
 * *pipeline* that got cut off), so this just re-runs the same
 * `run_post_recording_pipeline` a normal Stop uses, from the top. Simpler
 * than resuming from the exact last-completed step (transcription is
 * fast — thanks to chunking — and idempotent to redo), and correct
 * regardless of whether the crash landed mid-transcription or
 * mid-extraction.
 */
async resumeStuckProcessing(conversationId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_stuck_processing", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-runs one conversation's extraction turn (idempotent
 * re-extraction), then — same as the post-recording pipeline — attempts the
 * project-memory auto-refresh trigger. `force_overwrite` is sourced from the
 * UI's "Overwrite your edits?" modal confirmation (`pages/04`); the auto
 * pipeline always calls this with `force_overwrite=false`.
 */
async conversationRetryStep(conversationId: string, step: RetryableStep, forceOverwrite: boolean) : Promise<Result<RegenerateOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_retry_step", { conversationId, step, forceOverwrite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConversationDetail(conversationId: string) : Promise<Result<ConversationDetail, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversation_detail", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles one `<ActionItemRow>` checkbox. Thin wrapper over
 * the storage method — Conversation Detail is the first UI surface that
 * renders action items at all.
 */
async conversationSetActionItemDone(actionItemId: string, done: boolean) : Promise<Result<ActionItem, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_set_action_item_done", { actionItemId, done }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renames a conversation (`<EditableTitle>`).
 */
async conversationSetTitle(conversationId: string, title: string) : Promise<Result<Conversation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_set_title", { conversationId, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persists Conversation Detail's Notes tab — the
 * recording screen's notes draft is saved here rather than staying
 * local-only.
 */
async conversationSetNotes(conversationId: string, notes: string) : Promise<Result<Conversation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_set_notes", { conversationId, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Conversation Detail's overflow-menu Delete (12_CORNER_CASES.md
 * "Data delete flows"). Thin wrapper: reuses the same atomic,
 * crash-resumable `enqueue_conversation_delete` path everything else in
 * the app uses (crash-recovery's Discard actions, in
 * `commands::recording`), so there is nothing new to get wrong here.
 */
async conversationDelete(conversationId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_delete", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a user-authored action item — the other way an `action_items`
 * row can exist is via extraction.
 */
async conversationCreateActionItem(conversationId: string, text: string) : Promise<Result<ActionItem, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_create_action_item", { conversationId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists conversations — `project_id: None` returns every conversation
 * regardless of project (Dashboard's "Recent Conversations", which is the
 * permanent home for unfiled conversations, not a stopgap), `Some(id)`
 * scopes to one project (Project Detail), and
 * `unfiled_only` scopes to conversations with no project at all.
 * 
 * Returns one page plus the total it was drawn from, so the caller can
 * render `Conversations (128)` and `108 remaining` without a second round
 * trip or a second source of truth.
 */
async listConversations(filter: ConversationFilter) : Promise<Result<Page<Conversation>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_conversations", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Assigns or reassigns a conversation's project, `None` meaning "no
 * project" — always a valid, permanent choice, never
 * gated on recording having stopped. Purely a DB update: conversation
 * directories are flat and keyed by id alone
 * (`fs::paths::recordings_root`), so there is no filesystem move tied to
 * this anymore. If this conversation is still actively recording, also
 * updates the live session's cached `project_id` — `stop_recording`'s
 * post-pipeline memory-refresh trigger reads that cached value to know
 * which project's memory doc to refresh (the project chip is
 * editable "before, during, after recording, or never").
 */
async conversationSetProject(conversationId: string, projectId: string | null) : Promise<Result<Conversation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_set_project", { conversationId, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manual refresh: flushes the pending-count immediately (union of whatever
 * conversations are currently pending for this project) and enqueues
 * `refresh_project_memory`. Debounced — a repeat call inside the
 * 5s window is a no-op that returns the already-enqueued handle instead of
 * starting a second refresh.
 */
async projectRefreshMemory(projectId: string) : Promise<Result<RefreshHandle, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_refresh_memory", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every non-deleted project, pinned first then last-active (`list_projects`'s
 * ordering) — backs the left nav's project tree.
 */
async listProjects() : Promise<Result<Project[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Real "+New Project" (replaces the earlier stub toast). Name-only in v1 — the
 * description field exists on the model but no UI writes it yet.
 */
async createProject(name: string) : Promise<Result<Project, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProject(projectId: string) : Promise<Result<Project, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Project Detail's inline-editable name (`<EditableProjectName>`,
 * mirroring Conversation Detail's `<EditableTitle>`). Rejects an
 * empty/whitespace-only name the same way `update_conversation_title`
 * does — `StorageService::update_project` itself doesn't validate this,
 * so the check lives here.
 */
async projectSetName(projectId: string, name: string) : Promise<Result<Project, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_set_name", { projectId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `None` when no refresh has run for this project yet (Project Memory
 * pane's "empty until first conversation is processed" state, per
 * `pages/05_PROJECT_MEMORY.md` §1 Overview).
 */
async getProjectMemory(projectId: string) : Promise<Result<ProjectMemory | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project_memory", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Just the size of a scope, for surfaces that render a number and no rows —
 * the left nav's per-project badges and the Recordings header. A cheap
 * count-only endpoint avoids fetching every row and taking `.length`, per
 * expanded project, on every nav render.
 */
async countConversations(filter: ConversationFilter) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_conversations", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A standalone action item — Home's "+" (`project_id: None`) or a Project
 * page's "+" (`project_id: Some`). No conversation, so no `conversationId`
 * param: there is nothing for this command to attach the item to.
 * 
 * `assignee_hint`/`assignee_is_self` let Home self-assign in the same write
 * that creates the row — see `insert_standalone_action_item`'s comment for
 * why that has to be atomic rather than a create-then-assign chain.
 */
async createStandaloneActionItem(projectId: string | null, text: string, assigneeHint: string | null, assigneeIsSelf: boolean) : Promise<Result<ActionItemWithSource, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_standalone_action_item", { projectId, text, assigneeHint, assigneeIsSelf }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One page of the action items assigned to the user, across every project
 * and every unfiled conversation — Home's "Your to-dos". `done` is an exact
 * match, not a superset flag: Home's Open/Done tabs are two exclusive
 * queries, never "everything," so this command's own param is a plain
 * mandatory `bool` (unlike the storage-layer `ActionItemFilter.done`, which
 * is `Option<bool>` for the MCP tool's "no restriction" case).
 */
async listMyActionItems(done: boolean, limit: number | null, offset: number) : Promise<Result<Page<ActionItemWithSource>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_my_action_items", { done, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sets who owes an action item. Free text, not a contact id, and not
 * validated against anything: there is no contacts table until v1.3, and the
 * correction path for a wrong guess must be cheaper than the guess. An empty
 * or whitespace-only string means "unassigned" and is normalised to `None`
 * here rather than stored as `""`, which would render as an empty badge.
 */
async setActionItemAssignee(itemId: string, assigneeHint: string | null, assigneeIsSelf: boolean) : Promise<Result<ActionItem, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_action_item_assignee", { itemId, assigneeHint, assigneeIsSelf }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sets who owes the *answer* to an open question. Never touches
 * `raised_by_hint` — who asked is a fact about the past.
 */
async setOpenQuestionOwner(questionId: string, ownerHint: string | null, ownerIsSelf: boolean) : Promise<Result<OpenQuestion, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_open_question_owner", { questionId, ownerHint, ownerIsSelf }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Marks an open question answered by this conversation, or reopens it.
 */
async setOpenQuestionResolved(questionId: string, resolvedByConversationId: string | null) : Promise<Result<OpenQuestion, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_open_question_resolved", { questionId, resolvedByConversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves a summary the user rewrote by hand.
 * 
 * Writing `summary.md` is all this needs to do: `memory::summary_is_user_edited`
 * decides whether a later regeneration may overwrite the file by comparing
 * its mtime against `extraction.json`'s, so the edit protects itself the
 * moment it lands. No flag to set and none to forget to set.
 */
async conversationSetSummary(conversationId: string, summaryMarkdown: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_set_summary", { conversationId, summaryMarkdown }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes one extracted item the model got wrong.
 * 
 * Returns the deleted row whole so the undo toast can hand it straight back
 * to [`conversation_restore_extraction_item`] — the item comes back with its
 * assignee, due date and quote intact rather than as a bare line of text.
 */
async conversationDeleteExtractionItem(kind: ExtractionKind, itemId: string) : Promise<Result<DeletedExtraction, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_delete_extraction_item", { kind, itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Undo for [`conversation_delete_extraction_item`].
 */
async conversationRestoreExtractionItem(item: DeletedExtraction) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_restore_extraction_item", { item }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rewrites an extracted item's text, which also claims it: the row stops
 * being model-owned, so regenerating leaves it alone. Returns nothing —
 * the caller already knows the text it sent, and every list that shows this
 * row patches its own cache optimistically.
 */
async conversationSetExtractionText(kind: ExtractionKind, itemId: string, text: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_set_extraction_text", { kind, itemId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Eligible projects (>=5 conversations), sorted by recent activity,
 * each with its decision/open-question counts over the last
 * `PULSE_WINDOW_DAYS` days. One round trip — the alternative is one query
 * per eligible project from the frontend, which is the same N+1 shape
 * already removed from the conversation lists.
 */
async dashboardGetProjectPulse() : Promise<Result<ProjectPulseItem[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dashboard_get_project_pulse") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async projectGetMemoryStatus(projectId: string) : Promise<Result<ProjectMemoryStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_get_memory_status", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One page of a project's action items — the model-derived ones (via the
 * conversations join) and the standalone ones added directly from this
 * page's own "+". `done` is an exact match — see `list_my_action_items`'s
 * doc comment for why this command's param is a plain mandatory `bool`
 * rather than the storage layer's `Option<bool>`.
 */
async projectListActionItems(projectId: string, done: boolean, limit: number | null, offset: number) : Promise<Result<Page<ActionItemWithSource>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_list_action_items", { projectId, done, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One page of a project's decision log, oldest first (the order
 * `list_decisions_global` guarantees — a decision log reads forwards).
 */
async projectListDecisions(projectId: string, limit: number | null, offset: number) : Promise<Result<Page<Decision>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_list_decisions", { projectId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One page of a project's open questions, newest first.
 * `resolved_only` backs the Open/Resolved split. The `include_resolved`
 * filter existed for a while with no caller ever setting it, so every
 * resolved question stayed in the Open list forever; the split needs the
 * complementary predicate too, so each tab pages and counts on its own.
 */
async projectListOpenQuestions(projectId: string, resolvedOnly: boolean, limit: number | null, offset: number) : Promise<Result<Page<OpenQuestionWithSource>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_list_open_questions", { projectId, resolvedOnly, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The actual `#[tauri::command]` — a thin wrapper over `send_prompt`, see
 * its doc comment for why the logic lives in a plain function instead.
 */
async chatSendPrompt(target: SendTarget, text: string, channel: TAURI_CHANNEL<AgentEvent>) : Promise<Result<ChatSendPromptAck, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_send_prompt", { target, text, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops the in-flight turn for `session_id` and kills its runner process
 * (design doc §2.4 — the runner is a persistent whole-process-per-session
 * primitive in v1, so "cancel a turn" and "cancel the process" are the same
 * operation; `ChatRegistry::evict` guarantees the next message in this
 * session cold-starts a fresh process rather than writing to a dead one's
 * stdin).
 */
async chatCancelTurn(sessionId: string, turnId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_cancel_turn", { sessionId, turnId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns raw journaled events for a session, oldest-first (design doc
 * §2.3.1) — deliberately *not* pre-grouped into `Message`s here.
 * Grouping consecutive `token_delta`s into one assistant message and
 * pairing `tool_call`/`tool_result` is a pure, side-effect-free projection
 * that belongs on the frontend next to the render logic it feeds
 * (`projectHistory` in `src/components/app/chat/`), not duplicated in Rust.
 */
async chatGetSessionHistory(sessionId: string, beforeSeq: number | null, limit: number) : Promise<Result<ChatEventRecord[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_get_session_history", { sessionId, beforeSeq, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a chat and its whole transcript.
 * 
 * Evicts the live runner first: without that the `claude` process leaks
 * until the app quits, and an in-flight `forward_turn` keeps journaling
 * against a row that no longer exists (which fails as `NotFound` and is
 * swallowed as a warning). Journal rows go with the row via `ON DELETE
 * CASCADE`.
 */
async chatDeleteSession(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_delete_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renames a chat session (design doc US-7). Rejects an empty/
 * whitespace-only title — see `StorageService::update_chat_session_title`.
 */
async chatRenameSession(sessionId: string, title: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_rename_session", { sessionId, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists past chat sessions, newest-updated first, for the history browser
 * (design doc US-8) — every session for every scope; "New chat" never
 * removes an old one from this list, it just adds a new row.
 */
async chatListSessions(beforeUpdatedAt: number | null, limit: number) : Promise<Result<ChatSession[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_list_sessions", { beforeUpdatedAt, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The most recently used session for a scope, if one has ever been opened
 * — without creating one. Lets the frontend
 * know a real backend session id to default into for a scope *before* the
 * user sends a first message this app session — needed to fetch history
 * for a scope you've chatted in before, and the missing piece that let
 * `chatSessionId` go permanently unset (nothing ever populated it on
 * mount, only a send's ack could, and a send required it to already be
 * set — a deadlock; found while wiring the redesigned chat UI to this
 * command). This is only ever a starting point the frontend may switch
 * away from (e.g. reopening an older session from history) — `send_prompt`
 * always takes the exact session id the frontend is currently showing,
 * never re-derives one from scope.
 */
async chatResolveSession(scope: ChatScopeInput) : Promise<Result<ChatSession | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_resolve_session", { scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * v1 has exactly one transcription model, but this returns a `Vec` rather
 * than a single value from day one — `list_projects`/`list_conversations`
 * already establish "a plural getter, even when there's currently one
 * row" as this codebase's own convention, and it means a second model
 * later is an added entry, never a shape change either caller (onboarding
 * today, a Settings model picker later) has to adapt to.
 */
async listTranscriptionModels() : Promise<TranscriptionModelInfo[]> {
    return await TAURI_INVOKE("list_transcription_models");
},
async onboardingGetStatus() : Promise<Result<OnboardingStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_get_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Welcome screen requires a first name before either of its
 * exits (Continue, "I've used Mnemos before") proceeds — attribution
 * (`memory::self_contact`) depends on it, so the "zero form-filling"
 * `01_ONBOARDING.md` goal lost to that. `last_name` stays optional. The
 * command itself still accepts `None` for either and doesn't enforce the
 * requirement server-side: the gate is UX policy for the funnel, not an
 * invariant of stored settings, so a future editable-in-Settings path isn't
 * blocked from clearing the name if that's ever wanted.
 */
async onboardingSetUserName(firstName: string | null, lastName: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_set_user_name", { firstName, lastName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called once, landing on Dashboard — sets the flag the root route's
 * `beforeLoad` guard checks so onboarding never shows again.
 */
async onboardingComplete() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_complete") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dashboard's checklist "Connect" click (or its own dismiss control) — see
 * `OnboardingStatus.calendar_checklist_dismissed`'s doc comment.
 */
async onboardingDismissCalendarChecklist() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_dismiss_calendar_checklist") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Screen 2 — proactive CLI detection, reusing the same PATH-scan
 * `find_claude_binary` already uses when a chat/extraction runner actually
 * spawns. Does not attempt to verify login state (see `RunnerKind::detect`'s
 * doc comment for why) — a not-logged-in CLI is caught by the existing
 * runtime error path the first time it's actually used, not gated here.
 */
async onboardingCheckClaudeCli() : Promise<RunnerDetection> {
    return await TAURI_INVOKE("onboarding_check_claude_cli");
},
async onboardingCheckPermissions() : Promise<Result<PermissionStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_check_permissions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async onboardingRequestMicPermission() : Promise<Result<PermissionState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_request_mic_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async onboardingRequestScreenPermission() : Promise<Result<PermissionState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_request_screen_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deep-links to the exact System Settings pane for a denied permission
 * (`01_ONBOARDING.md` Screen 3's "expandable 'How to fix in System
 * Settings'"). Best-effort: opening a settings pane is not something a
 * failure here should block onboarding on, so this never returns
 * `AppError` — it logs and no-ops instead.
 */
async onboardingOpenSystemSettings(pane: SettingsPane) : Promise<void> {
    await TAURI_INVOKE("onboarding_open_system_settings", { pane });
},
/**
 * Screen 4 — subscribes to `model_download_progress` and immediately pushes
 * a synchronous status snapshot first, so a screen that mounts after the
 * download already finished (or already started, due to the eager
 * `warm_up()`) doesn't sit on a stuck 0% bar waiting for a change event that
 * may never come again. No separate "start" command exists — see
 * `ModelDownloadStatus`'s doc comment for why.
 */
async onboardingSubscribeModelDownload(channel: TAURI_CHANNEL<ModelDownloadStatusResponse>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_subscribe_model_download", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trackEvent(event: string, properties: Partial<{ [key in string]: TrackPropertyValue }>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("track_event", { event, properties }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called by the quit-confirmation dialog after it has dealt with the
 * in-flight recording (stopped it, or decided to abandon it). Deliberately
 * unguarded: the guard already ran, and the user answered it.
 */
async trayQuitConfirmed() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_quit_confirmed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveals the window once the frontend has actually painted.
 * 
 * The window is created hidden (`tauri.conf.json`'s `"visible": false`).
 * Shown at creation instead, the user watches an empty 1200x800 frame
 * appear, jump to maximized as the saved geometry is restored, and only then
 * fill in — which reads as the app opening twice.
 * 
 * Idempotent: [`show_main_window`] is a no-op on an already-visible window,
 * so the launch fallback in `lib.rs` racing the frontend costs nothing.
 */
async appReady() : Promise<void> {
    await TAURI_INVOKE("app_ready");
},
async updaterCheckNow() : Promise<Result<UpdateCheckResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("updater_check_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Downloads and installs the update. Does not itself relaunch — the
 * frontend calls `@tauri-apps/plugin-process`'s `relaunch()` right after
 * this resolves, so a failed install never leaves the banner claiming a
 * restart is about to happen. Re-checks rather than reusing a prior
 * `Update` handle from `updater_check_now` — the plugin's `Update` type
 * isn't the kind of thing worth threading across a separate IPC round trip
 * and into `AppState` just to save one network call.
 * 
 * `force: false` and a recording is in flight → refused via `Validation`
 * with `field: "active_recording"`, so the frontend can show a "this will
 * end your current recording" confirmation and retry with `force: true`
 * rather than silently killing an in-progress capture.
 */
async updaterInstallAndRelaunch(force: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("updater_install_and_relaunch", { force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updaterGetSettings() : Promise<Result<UpdaterSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("updater_get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updaterSetAutoCheckEnabled(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("updater_set_auto_check_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async meetingDetectionGetSettings() : Promise<Result<MeetingDetectionSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("meeting_detection_get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async meetingDetectionSetEnabled(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("meeting_detection_set_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Overlay's Start Recording button. Deliberately does **not** call
 * `commands::recording::start_recording` directly — per AGENTS.md
 * ("Starting a recording is a frontend-owned sequence, not a single
 * command"), that would record audio while the store still reads `idle`
 * and no session would show anywhere. Instead this reuses the exact same
 * `TrayStartRecording` event the tray's own "start from outside the
 * frontend" path already emits — one implementation of "start recording
 * from outside the app's own UI", not a second one.
 * 
 * Always unfiled (`project_id: None`) — the overlay had a project picker
 * once, removed because clicking anywhere on this window (a native
 * `<select>` included) activates the whole app regardless of window
 * `focusable`/`always_on_top` settings, a macOS AppKit behavior with no
 * public Tauri/tao escape hatch short of a raw-Cocoa `NSPanel` rewrite —
 * so a project chooser here bought nothing a plain click didn't already
 * cost. Filing into a project is still one click away, from the main
 * window this brings forward.
 */
async meetingNotificationStartRecording() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("meeting_notification_start_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async meetingNotificationDismiss(bundleId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("meeting_notification_dismiss", { bundleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The overlay sizes its own window: the card's height is decided by CSS
 * (icon, two lines of text, a button row), and the webview is the only
 * place that knows what that came out to. Called on mount and whenever the
 * card resizes, so the window is exactly as tall as its content instead of
 * whatever number was last hardcoded on this side.
 */
async meetingNotificationResize(height: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("meeting_notification_resize", { height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The user pointing us at a `claude` we could never have found.
 * 
 * Detection scans `PATH` and then the locations the CLI's own installers
 * use, which covers a normal machine but cannot cover a managed one — an
 * Amazon-issued laptop keeps the binary in `~/.toolbox/bin`, and no list of
 * guesses will ever contain every such path. This is the escape hatch, and
 * on a corporate machine it is the only thing that works.
 * 
 * Validates before storing: a path saved here is used for every subsequent
 * spawn, so accepting a typo would turn one clear "that file doesn't exist"
 * into a chat that fails later for no visible reason.
 */
async runnerSetClaudePath(path: string | null) : Promise<Result<RunnerDetection, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("runner_set_claude_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runnerGetClaudePath() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("runner_get_claude_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What Settings and onboarding render. Unlike `onboarding_check_claude_cli`
 * this reports sign-in state too, so "installed but signed out" stops
 * looking identical to "ready".
 */
async runnerHealth() : Promise<RunnerHealth> {
    return await TAURI_INVOKE("runner_health");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
conversationReady: ConversationReady,
liveTranscriptionWarmup: LiveTranscriptionWarmup,
processingProgress: ProcessingProgress,
projectMemoryRefreshFailed: ProjectMemoryRefreshFailed,
projectMemoryUpdated: ProjectMemoryUpdated,
recordingWarning: RecordingWarning,
trayConfirmQuit: TrayConfirmQuit,
trayPauseRecording: TrayPauseRecording,
trayResumeRecording: TrayResumeRecording,
trayStartRecording: TrayStartRecording,
trayStopRecording: TrayStopRecording
}>({
conversationReady: "conversation-ready",
liveTranscriptionWarmup: "live-transcription-warmup",
processingProgress: "processing-progress",
projectMemoryRefreshFailed: "project-memory-refresh-failed",
projectMemoryUpdated: "project-memory-updated",
recordingWarning: "recording-warning",
trayConfirmQuit: "tray-confirm-quit",
trayPauseRecording: "tray-pause-recording",
trayResumeRecording: "tray-resume-recording",
trayStartRecording: "tray-start-recording",
trayStopRecording: "tray-stop-recording"
})

/** user-defined constants **/



/** user-defined types **/

export type ActionItem = { id: string; 
/**
 * `None` for a standalone item added from Home or a Project page. The
 * column has always been nullable; this field claimed otherwise and
 * sqlx's lenient TEXT decode quietly handed back `""` for those rows
 * instead of failing, so a caller building a link from it would have
 * produced `/conversation/` and a dead route.
 */
conv_id: string | null; text: string; assignee_hint: string | null; 
/**
 * Whether `assignee_hint` is the app's own user rather than a real
 * name — see the column's migration comment. `assignee_hint` always
 * holds a name or `null`; this is the only place "is this me" lives.
 */
assignee_is_self: boolean; assignee_source: HintSource; due_hint: string | null; source_ts: number | null; done: boolean; added_manually: boolean; created_at: number; updated_at: number }
export type ActionItemWithSource = { id: string; 
/**
 * `None` for a standalone item (added from Home or a Project page, no
 * source conversation) — `project_id` below is where it's scoped
 * instead, when it has a scope at all.
 */
conv_id: string | null; project_id: string | null; text: string; assignee_hint: string | null; assignee_is_self: boolean; assignee_source: HintSource; due_hint: string | null; source_ts: number | null; done: boolean; created_at: number }
/**
 * The stream envelope. A discriminated union versioned by
 * shape, not an integer — consumers `match` and route unrecognized shapes
 * to `Notice{Info}` for forwards-compat.
 */
export type AgentEvent = 
/**
 * A slice of assistant text. Consumers append verbatim.
 */
{ kind: "token_delta"; turn_id: string; text: string } | 
/**
 * The model emitted a `tool_use` block. v1 has no Rust-side
 * tool-calling loop — the CLI resolves any MCP tool call itself, so
 * this is purely informational — logged, never dispatched, no matching
 * `ToolResult` will ever follow it.
 */
{ kind: "tool_call"; turn_id: string; call_id: string; tool_name: string; args: JsonValue; human_readable: string } | 
/**
 * Latent in v1 — reserved for a future Rust-side tool-calling loop.
 */
{ kind: "tool_result"; turn_id: string; call_id: string; ok: boolean; summary: string; raw: JsonValue } | 
/**
 * Latent in v1 — no tools ship, so the CLI never emits a
 * permission-request frame in practice.
 */
{ kind: "approval_request"; turn_id: string; request_id: string; tool_name: string; args: JsonValue; destructive: boolean } | 
/**
 * Free-form status message. Unrecognized shapes route here as `Info`.
 * 
 * The field is named `notice_kind`, not `kind` — the enum's own serde
 * tag (`#[serde(tag = "kind")]`) already claims `kind`, and
 * `specta`/`serde` reject a tag/field name collision.
 */
{ kind: "notice"; turn_id: string; notice_kind: NoticeKind; text: string } | 
/**
 * Terminal success. Consumers stop reading after this.
 */
{ kind: "complete"; turn_id: string; stop_reason: StopReason; usage: Usage } | 
/**
 * Terminal failure. Consumers stop reading after this.
 */
{ kind: "error"; turn_id: string; error: AppError }
export type AppError = { kind: "not_found"; entity: string; id: string } | { kind: "worker_unavailable"; retry_after_ms: number } | { kind: "permission_denied"; permission: string } | { kind: "network"; message: string; correlation_id: string } | { kind: "runner"; runner: string; message: string; correlation_id: string } | { kind: "storage"; message: string; correlation_id: string } | { kind: "validation"; message: string; field: string | null } | { kind: "model"; model: string; message: string; correlation_id: string } | 
/**
 * The runner reached the user's provider-side usage limit — a
 * *recoverable* refusal, distinct from `Runner` (which means the CLI
 * crashed, was misconfigured, or returned garbage). Kept separate
 * because the two need opposite user-facing treatment: `Runner` says
 * "something is broken", this says "come back when your limit resets;
 * nothing was lost".
 * 
 * `Display` is the bare message, no variant prefix — it is written to
 * `pipeline_state.error` and rendered verbatim to the user by
 * Conversation Detail's failure banner.
 */
{ kind: "runner_blocked"; runner: string; resets_at: number | null; message: string; correlation_id: string } | 
/**
 * The worker's own vocabulary calls this "cancelled" (`CANCELLED` in
 * `errors.py`, JSON-RPC code `-32020`), but its one producer today
 * (`agent_call.py`'s `_agent_call`) only ever raises it for a reverse-RPC
 * timeout, never a real user-initiated cancel — nothing in this app
 * exposes a cancel button that could produce this. `message` carries the
 * worker's actual reason (e.g. "agent timeout: ...") through rather than
 * discarding it: this used to be a fieldless variant with a fixed
 * `"operation cancelled"` Display string, which is what a user saw
 * (stored verbatim as `pipeline_error`, or surfaced via `describeError`)
 * with zero indication of what actually happened or why retrying might
 * work.
 */
{ kind: "cancelled"; message: string } | { kind: "internal"; message: string; correlation_id: string }
/**
 * One journal row's payload; this layer only guarantees
 * journal-then-projection atomicity around it.
 * `Type`: exposed to the frontend via
 * `chat_get_session_history` so `MessageList` can project real history.
 */
export type ChatEventRecord = { session_id: string; seq: number; ts: number; event_json: JsonValue }
export type ChatScopeInput = { scope_type: "everything" } | { scope_type: "project"; project_id: string } | { scope_type: "conversation"; conversation_id: string }
export type ChatScopeType = "everything" | "project" | "conversation"
export type ChatSendPromptAck = { session_id: string }
/**
 * `Type`: exposed to the frontend by
 * `chat_resolve_session`/`chat_list_sessions`.
 */
export type ChatSession = { 
/**
 * Mnemos' own id. Exists before any runner process does.
 */
id: string; runner_id: string | null; scope_type: ChatScopeType; scope_id: string | null; 
/**
 * The *runner's* own session id — Claude Code's `--session-id` /
 * `--resume` value. `None` until a runner has actually started for
 * this chat. Distinct from `id`; see the `chat_sessions` DDL.
 */
runner_session_id: string | null; title: string | null; 
/**
 * Durable items journaled for this chat. A projection for display —
 * never a source of `chat_journal.seq`.
 */
message_count: number; total_input_tokens: number; total_output_tokens: number; cost_micros: number; created_at: number; updated_at: number }
export type Conversation = { id: string; 
/**
 * Recordings never require a project — `None`
 * means unfiled, a first-class, permanent state, not a placeholder.
 */
project_id: string | null; title: string; started_at: number; ended_at: number | null; duration_s: number | null; status: ConversationStatus; runner_id: string | null; starred: boolean; archived: boolean; notes: string | null; deleted_at: number | null; created_at: number; updated_at: number }
/**
 * Everything Conversation Detail renders in one round
 * trip. `transcript`/`summary_markdown` are `None` until the pipeline has
 * written them (`transcribing`/`extracting` respectively) — the route
 * falls back to `<ProcessingOverlay>` + `processing-progress` events for
 * the in-between state, so a `None` here just means "not there yet", not
 * an error.
 */
export type ConversationDetail = { conversation: Conversation; 
/**
 * `None` when the conversation has no project assigned — a permanent,
 * valid state, not "not loaded yet".
 */
project_name: string | null; pipeline_step: PipelineStep | null; pipeline_error: string | null; transcript: TranscriptDoc | null; summary_markdown: string | null; action_items: ActionItem[]; decisions: Decision[]; open_questions: OpenQuestion[] }
/**
 * Every field past `include_archived` exists to make `list_conversations`
 * callers bounded. `limit: None` still means
 * "every row" and is deliberately kept, not removed — a few internal callers
 * (crash-recovery scans) genuinely want the whole set and are bounded by
 * something other than library size. What is *not* allowed is a UI surface
 * leaving it `None`.
 */
export type ConversationFilter = { 
/**
 * `None` = every project (Everything scope). Note this is not the same
 * as `unfiled_only`: `None` includes filed *and* unfiled conversations.
 */
project_id: string | null; 
/**
 * `project_id IS NULL` — the Recordings page's "unfiled" scope
 * (unfiled is a permanent first-class state, never a project).
 */
unfiled_only: boolean; include_archived: boolean; starred_only: boolean; 
/**
 * Inclusive bounds on `started_at`.
 */
since: number | null; until: number | null; 
/**
 * Case-insensitive substring match on the title. Deliberately `LIKE`
 * rather than the FTS5 index: FTS is a ranked keyword search over four
 * content kinds and cannot be composed with these filters or with
 * `LIMIT`/`OFFSET` paging without ranking the whole corpus first. Title
 * filtering here is a *filter*, not a search — ⌘K remains the search.
 */
title_query: string | null; order: ConversationOrder; 
/**
 * `None` = unbounded. Every UI caller must set it.
 */
limit: number | null; offset: number }
/**
 * Sort order for [`ConversationFilter`]. Sorting is a *query* concern, not a
 * view concern: once a list is a page rather than the whole set, sorting it
 * in the client sorts only the rows that happen to be loaded, which is worse
 * than not sorting at all.
 */
export type ConversationOrder = 
/**
 * Most recent first — every list surface's default.
 */
"started_desc" | "started_asc"
/**
 * A conversation's post-recording pipeline (transcribe -> diarize ->
 * extract -> save) finished; the summary/detail view has data to show.
 * `project_id` is `None` for an unfiled conversation (deliberate — unfiled
 * is first-class, not an error state).
 */
export type ConversationReady = { conversation_id: string; project_id: string | null }
export type ConversationStatus = "recording" | "processing" | "ready" | "failed"
/**
 * Read model for a `decisions` row, following `ActionItem`'s shape.
 */
export type Decision = { id: string; 
/**
 * `None` for a standalone decision (schema supports it — see
 * `action_items`' migration comment — though nothing creates one yet;
 * only action items currently have a "+" for adding one manually).
 */
conv_id: string | null; project_id: string | null; statement: string; quote: string | null; decided_by_hint: string | null; decided_by_is_self: boolean; source_ts: number | null; added_manually: boolean; created_at: number }
/**
 * A row lifted out of one of the extraction tables, whole, so it can be put
 * back byte-for-byte.
 * 
 * Adjacently tagged rather than three separate delete commands: the three
 * tables carry genuinely different columns, and an enum keeps the caller —
 * and the generated TypeScript — from having to know which one it is holding
 * before it can hand it back.
 */
export type DeletedExtraction = { kind: "action_item"; item: ActionItem } | { kind: "decision"; item: Decision } | { kind: "open_question"; item: OpenQuestion }
/**
 * Which of the three extracted-item tables a row lives in.
 * 
 * Exists so delete and edit are one code path across all three rather than
 * three near-identical ones: the tables differ only in their text column, and
 * a closed enum makes "some fourth kind" unrepresentable instead of a runtime
 * string comparison that silently matches nothing. The wire values are the
 * `deleted_extractions.kind` values verbatim.
 */
export type ExtractionKind = "action_item" | "decision" | "open_question"
/**
 * Provenance of a `*_hint` a person can edit. The distinction is load-bearing:
 * `replace_extraction_rows` rebuilds every model-derived row on a
 * re-extraction, so without this flag a user's correction is indistinguishable
 * from the guess it replaced and gets thrown away with it.
 */
export type HintSource = "model" | "manual"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * 100ms mic/system dB sample streamed to the React level meter, mirroring
 * `LevelSample` in `src/ipc/streams.ts` field-for-field.
 */
export type LevelSample = { session_id: number; mic_db: number; system_db: number }
/**
 * Forwards the Python worker's `live_transcription_warmup` notification.
 * `ready: false` means live transcription is blocked on `ParakeetModel`
 * warm-up; `ready: true` clears it. Fired once per state transition.
 */
export type LiveTranscriptionWarmup = { conversation_id: string; ready: boolean }
export type MeetingDetectionSettings = { enabled: boolean }
export type ModelDownloadStatusResponse = { model_id: string; received_bytes: number; total_bytes: number; done: boolean }
export type NoticeKind = "Info" | "Warn" | "RateLimit"
export type OnboardingStatus = { has_onboarded: boolean; user_first_name: string | null; user_last_name: string | null; 
/**
 * Dashboard's first-run checklist (`01_ONBOARDING.md`'s "Landing"
 * section) has two rows: "record your first conversation" — derived
 * for free from whether any conversation exists, never stored here —
 * and "connect your calendar," which this field tracks. Calendar
 * *integration* itself is a later release; v1 has nothing to actually
 * connect, so "Connect" navigates to the `/integrations` stub and
 * clicking it is treated as satisfying the row (there is no real
 * "connected" signal in v1 to check against instead).
 */
calendar_checklist_dismissed: boolean }
/**
 * Read model for an `open_questions` row — same rationale as [`Decision`].
 */
export type OpenQuestion = { id: string; conv_id: string; question: string; raised_by_hint: string | null; raised_by_is_self: boolean; 
/**
 * Who owes the answer — distinct from `raised_by_hint`, which records
 * who asked and is never edited. The model never populates this in v1.
 */
owner_hint: string | null; owner_is_self: boolean; owner_source: HintSource; source_ts: number | null; resolved_conv_id: string | null; resolved_at: number | null; added_manually: boolean; created_at: number }
export type OpenQuestionWithSource = { id: string; 
/**
 * `None` for a standalone question — same rationale as
 * [`ActionItemWithSource::conv_id`].
 */
conv_id: string | null; project_id: string | null; question: string; raised_by_hint: string | null; raised_by_is_self: boolean; 
/**
 * Who owes the answer — distinct from `raised_by_hint`, which records
 * who asked and is never edited. The model never populates this in v1.
 */
owner_hint: string | null; owner_is_self: boolean; owner_source: HintSource; source_ts: number | null; resolved_conv_id: string | null; resolved_at: number | null; created_at: number }
/**
 * One page of a list, plus the size of the full result set the page was
 * drawn from. `total` is what lets a section title read `Conversations (128)`
 * and a reveal control read `108 remaining` without loading 128 rows to
 * count them — it is computed by a `COUNT(*)` over the same filter, in the
 * same call, so the count and the rows can never disagree.
 */
export type Page<T> = { items: T[]; total: number }
export type PermissionState = "granted" | "denied" | "undetermined" | 
/**
 * Windows: v1 has no verified proactive check for this permission (see
 * module doc). Onboarding treats this the same as `Granted` for gating
 * purposes — never blocks Continue on something it cannot actually
 * verify — while still rendering distinctly so the UI doesn't claim a
 * grant that was never confirmed.
 */
"not_applicable"
export type PermissionStatus = { mic: PermissionState; screen: PermissionState }
export type PipelineStep = "finalizing" | "transcribing" | "extracting" | "done" | "failed"
/**
 * Reply from [`ping`]. `worker_ready` is hard-coded `false` — the field
 * exists so the shape doesn't change if it's wired to real worker-readiness
 * later.
 */
export type Pong = { app_version: string; worker_ready: boolean }
/**
 * One tick of a conversation's post-recording pipeline. `pct` is `None` for
 * steps whose duration cannot be measured — saving the recording (sub-second)
 * and extraction (a streaming model call with no fraction to read); only
 * `transcribing` reports a real fraction, fed from the worker's per-chunk
 * `job_progress` reports. `status` is always one of `running` | `done` |
 * `failed` at every call site today, but stays `String` rather than an enum
 * here to keep this struct's wire shape identical to what every caller of
 * `emit_progress` already sends — narrowing it is a separate decision.
 */
export type ProcessingProgress = { conversation_id: string; step: string; status: string; pct: number | null; 
/**
 * Why it failed, in words meant for the user — `None` for every status
 * other than `failed`.
 * 
 * Without this the UI could only say "Processing failed during
 * extracting", while the actual cause ("Claude Code is signed out. Run
 * `claude auth login`…") sat in the database and the log file. The
 * message is already written to `pipeline_step`, so a reload recovers
 * it; this carries it live.
 */
error: string | null }
export type Project = { id: string; name: string; description: string | null; pinned: boolean; archived: boolean; deleted_at: number | null; created_at: number; updated_at: number }
/**
 * `project_memory.json`'s shape (`pages/05_PROJECT_MEMORY.md`
 * "Storage schema"). Read-only render for now — the inline-editable
 * prose blocks the "Editing behavior" section describes come later.
 * 
 * `supersessions` stays untyped `Value` deliberately, matching
 * `ipc::python::ExtractMemoryResponse`'s own `Vec<Value>` — it comes
 * straight from the worker's LLM response with no schema enforced on it
 * anywhere in the pipeline, so a typed struct here would be one bad
 * generation away from failing to parse the whole file. Note `last_refresh_at`
 * is `unix_now()`, an `i64`, not the ISO-string the page doc's example
 * sketch showed — `memory::refresh_project` writes it directly, verified
 * against a real `project_memory.json` on disk.
 */
export type ProjectMemory = { overview_markdown: string; scope_drift_markdown: string; supersessions?: JsonValue[]; last_refresh_at: number | null; last_refresh_runner: string | null }
/**
 * A project's memory auto/manual-refresh (see [`ProjectMemoryUpdated`])
 * failed instead. Fired from the same 4 call sites, same
 * `err.to_string()` shape. No frontend listener exists for this one today
 * — it is typed and registered so the Rust side has a real event to emit
 * through rather than a bare string, but deliberately left unlistened;
 * adding a listener is a separate decision, not part of this migration.
 */
export type ProjectMemoryRefreshFailed = { project_id: string; error_kind: string }
/**
 * Whether this project's synthesized memory is behind, and whether the last
 * attempt to catch it up failed.
 * 
 * `pending_count` alone is not a problem signal: refreshes batch (see
 * `DEFAULT_REFRESH_EVERY_N`), so a couple of pending conversations is the
 * system working. `last_error` is the signal — it is set only when a refresh
 * actually failed and cleared the moment one succeeds. The UI shows its
 * staleness banner on `last_error.is_some()`, never on `pending_count > 0`,
 * so a healthy backlog stays invisible and the one message that matters
 * keeps its meaning.
 */
export type ProjectMemoryStatus = { 
/**
 * Conversations recorded since the last synthesis, i.e. how far behind
 * the Overview currently is.
 */
pending_count: number; 
/**
 * How many `pending_count` has to reach before the next rewrite. Sent
 * to the UI so it can state the cadence instead of leaving a stale
 * Overview looking broken.
 */
refresh_threshold: number; last_error: string | null }
/**
 * A project's memory doc (Decisions/Open Questions/Action Items) finished
 * an auto- or manual-refresh cycle. Fired from 4 call sites — retrying a
 * step, finishing a conversation's pipeline, setting a conversation's
 * project, and the manual "Refresh memory" action — all funneling through
 * `memory::maybe_auto_refresh`/`memory::refresh_project`, so this is one
 * event with one shape regardless of which triggered it.
 */
export type ProjectMemoryUpdated = { project_id: string; significant_change: boolean }
/**
 * Home's "Project pulse" (`02_DASHBOARD_AND_NAV.md`'s PROJECT PULSE
 * section) — one row per project active enough to be worth surfacing, with
 * what changed recently.
 */
export type ProjectPulseItem = { project_id: string; project_name: string; decisions_recent: number; open_questions_recent: number; last_activity_at: number | null }
/**
 * Emitted by the capture-watch task before the terminal `RECORDING ->
 * STOPPING` transition on a mic-disconnect, a sidecar crash (`Exited`), or a
 * disk-full write failure — the UI's cue to show a banner/toast with a
 * "View partial" affordance rather than silently losing the recording.
 * `kind` mirrors the capture error/exit vocabulary already defined
 * Rust-side (`mic_disconnected` | `sidecar_exited` | `disk_full`).
 */
export type RecordingWarning = { conversation_id: string; kind: string; message: string }
export type RecoverInterruptedResult = { 
/**
 * `true` when there was nothing worth recovering (see doc comment
 * below) and the row was auto-discarded instead of being sent through
 * the pipeline — the frontend shows a different toast for this case
 * than for "recovery started".
 */
discarded_no_audio: boolean }
export type RefreshHandle = { enqueued_at_ms: number; batch_signature: string }
/**
 * What a regeneration actually did, so the UI can say so instead of
 * guessing.
 * 
 * `summary_written` is `false` when the user had rewritten `summary.md` by
 * hand and it was therefore left alone — the ordinary, expected outcome of
 * regenerating a conversation whose summary you have edited, not an error.
 * Before this the command returned `()`, so the frontend announced "Summary
 * regenerated" in both cases, one of which was untrue.
 */
export type RegenerateOutcome = { summary_written: boolean }
export type RetryableStep = "extraction"
export type RunnerDetection = { installed: boolean; path: string | null }
/**
 * Whether a runner can actually do work right now, as a single value every
 * runner reports the same way.
 * 
 * Exists because "is the CLI installed" was never the whole question. A
 * signed-out CLI is installed, on PATH, and completely unable to produce a
 * summary — and the way that used to surface was a substring search of
 * stderr after a turn had already died. That guess is gone: the same check
 * now answers both before a spawn and after an unexpected exit, so there is
 * one source of truth rather than two that can drift. Claude answers via
 * `claude auth status --json`; codex will answer it its own way. The
 * variants are deliberately vendor-neutral so the UI can render one set of
 * states for any runner.
 */
export type RunnerHealth = { state: "ready"; version: string | null; account: string | null; plan: string | null } | { state: "not_installed" } | { state: "not_logged_in" } | 
/**
 * Usage limit or quota exhaustion — installed and authenticated, just
 * refusing work for now.
 */
{ state: "blocked"; resets_at: number | null } | 
/**
 * The check itself could not be completed (timeout, unparsable output).
 * Deliberately distinct from `NotLoggedIn`: telling someone to sign in
 * when we simply could not tell sends them to fix the wrong thing.
 */
{ state: "unknown"; detail: string }
/**
 * Where a prompt is going. Two variants rather than an optional
 * `session_id` beside an optional `scope`, so "a session id *and* a
 * contradicting scope" is not a state a caller can express.
 * 
 * `NewChat` carries a caller-minted `session_id`. The frontend mints it so
 * local state (draft, streaming buffer, outbox) keys off the real id from
 * the first keystroke rather than a placeholder that must later be
 * re-keyed, and so a double-fired or retried first send resolves to the
 * same chat instead of creating a second one.
 */
export type SendTarget = { kind: "new_chat"; session_id: string; scope: ChatScopeInput } | { kind: "existing"; session_id: string }
export type SettingsPane = "microphone" | "screen_recording"
export type StartRecordingResult = { session_id: number; conversation_id: string; 
/**
 * Always `None` at start — recordings never require a project (a
 * deliberate design decision). Assignable any time via the project chip.
 */
project_id: string | null; started_at_ms: number }
export type StopReason = "EndTurn" | "MaxTokens" | "StopSequence" | "ToolUse" | "Cancelled"
export type StopRecordingResult = { conversation_id: string; 
/**
 * True when the recording had under 5s of audio in both files —
 * mirrors `recover_interrupted_recording`'s and the capture-failure
 * path's identical threshold. The
 * conversation row is deleted rather than handed to a pipeline that
 * would either crash on an effectively-empty WAV or produce a useless
 * empty transcript. The frontend shows a toast and stays put instead
 * of navigating to a conversation that no longer exists.
 */
discarded_no_audio: boolean }
export type TrackPropertyValue = boolean | number | string
/**
 * One turn streamed to the React `LiveTranscriptStream` (`TranscriptChunk`,
 * mirrored field-for-field so `useLiveTranscriptChannel`
 * needs no change to consume the real transport).
 */
export type TranscriptChunk = { session_id: number; speaker_label_hint: string | null; text: string; ts_start_ms: number; ts_end_ms: number; 
/**
 * Client-side supersede-in-place logic already lives in
 * `useRecordingStore.appendTranscript` (matching `tsStartMs` +
 * text-prefix) — this transport never needs to flag it itself.
 */
superseded: boolean }
export type TranscriptDoc = { schema_version: number; conversation_id: string; duration_ms: number; turns: TranscriptTurn[] }
/**
 * One turn of `transcript.json`, verified against
 * `mnemos_worker/jobs/process_conversation.py::merge_transcripts`.
 * `speaker_label` is `"You"` (mic) / `"Them"` (system) only in v1 — no
 * diarization model runs yet, so `speaker_label_source` is always
 * `"source_file"` and `contact_id` is always `null`.
 */
export type TranscriptTurn = { text: string; ts_start_ms: number; ts_end_ms: number; source: string; speaker_label: string; speaker_label_source: string; contact_id: string | null }
export type TranscriptionModelInfo = { 
/**
 * Must match `PARAKEET_MODEL_ID` in `transcription.py` — see the
 * module doc comment above.
 */
id: string; display_name: string; 
/**
 * Display names, not ISO codes — this only ever feeds a UI list, and
 * "Ukrainian" needs no lookup table the way "uk" would.
 */
languages: string[] }
/**
 * Tray Quit found a recording in flight and is asking before exiting.
 * Payload-less, matching today's `app.emit(EVENT_CONFIRM_QUIT, ())`.
 */
export type TrayConfirmQuit = null
/**
 * Menu-bar Pause. Payload-less, matching today's `app.emit(EVENT_PAUSE, ())`.
 */
export type TrayPauseRecording = null
/**
 * Menu-bar Resume. Payload-less, matching today's `app.emit(EVENT_RESUME, ())`.
 */
export type TrayResumeRecording = null
/**
 * The tray's (or the meeting-detection overlay's) "start a recording from
 * outside the frontend's own UI" trigger — see `commands::tray::EVENT_START`'s
 * doc comment for why this one Rust-side event backs both entry points.
 * `project_id` mirrors `app.emit(EVENT_START, json!({ "project_id": ... }))`'s
 * shape exactly; `None` for the tray's plain Start item, `Some` for a
 * "start in project X" submenu item or the meeting overlay's chosen project.
 */
export type TrayStartRecording = { project_id: string | null }
/**
 * Menu-bar Stop. Payload-less, matching today's `app.emit(EVENT_STOP, ())`.
 */
export type TrayStopRecording = null
export type UpdateCheckResult = { available: boolean; version: string | null; notes: string | null; checked_at: number }
export type UpdaterSettings = { auto_check_enabled: boolean; last_checked_at: number | null }
export type Usage = { input_tokens: number; output_tokens: number; cache_creation_input_tokens: number | null; cache_read_input_tokens: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
