/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BareRouteImport } from './routes/_bare'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as BareOnboardingRouteImport } from './routes/_bare.onboarding'
import { Route as AppConversationConversationIdRouteImport } from './routes/_app.conversation.$conversationId'
import { Route as AppProjectProjectIdRouteImport } from './routes/_app.project.$projectId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BareRoute = BareRouteImport.update({
  id: '/_bare',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const BareOnboardingRoute = BareOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => BareRoute,
} as any)
const AppConversationConversationIdRoute =
  AppConversationConversationIdRouteImport.update({
    id: '/conversation/$conversationId',
    path: '/conversation/$conversationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectProjectIdRoute = AppProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/contacts': typeof AppContactsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/settings': typeof AppSettingsRoute
  '/onboarding': typeof BareOnboardingRoute
  '/conversation/$conversationId': typeof AppConversationConversationIdRoute
  '/project/$projectId': typeof AppProjectProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/contacts': typeof AppContactsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/settings': typeof AppSettingsRoute
  '/onboarding': typeof BareOnboardingRoute
  '/conversation/$conversationId': typeof AppConversationConversationIdRoute
  '/project/$projectId': typeof AppProjectProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_bare': typeof BareRouteWithChildren
  '/_app/contacts': typeof AppContactsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_bare/onboarding': typeof BareOnboardingRoute
  '/_app/': typeof AppIndexRoute
  '/_app/conversation/$conversationId': typeof AppConversationConversationIdRoute
  '/_app/project/$projectId': typeof AppProjectProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/integrations'
    | '/settings'
    | '/onboarding'
    | '/conversation/$conversationId'
    | '/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/integrations'
    | '/settings'
    | '/onboarding'
    | '/conversation/$conversationId'
    | '/project/$projectId'
  id:
    | '__root__'
    | '/_app'
    | '/_bare'
    | '/_app/contacts'
    | '/_app/integrations'
    | '/_app/settings'
    | '/_bare/onboarding'
    | '/_app/'
    | '/_app/conversation/$conversationId'
    | '/_app/project/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  BareRoute: typeof BareRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_bare': {
      id: '/_bare'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_bare/onboarding': {
      id: '/_bare/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof BareOnboardingRouteImport
      parentRoute: typeof BareRoute
    }
    '/_app/conversation/$conversationId': {
      id: '/_app/conversation/$conversationId'
      path: '/conversation/$conversationId'
      fullPath: '/conversation/$conversationId'
      preLoaderRoute: typeof AppConversationConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$projectId': {
      id: '/_app/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AppProjectProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContactsRoute: typeof AppContactsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConversationConversationIdRoute: typeof AppConversationConversationIdRoute
  AppProjectProjectIdRoute: typeof AppProjectProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactsRoute: AppContactsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppConversationConversationIdRoute: AppConversationConversationIdRoute,
  AppProjectProjectIdRoute: AppProjectProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BareRouteChildren {
  BareOnboardingRoute: typeof BareOnboardingRoute
}

const BareRouteChildren: BareRouteChildren = {
  BareOnboardingRoute: BareOnboardingRoute,
}

const BareRouteWithChildren = BareRoute._addFileChildren(BareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  BareRoute: BareRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
